[tools]
act = "latest"
aws-cli = "latest"
claude = "latest"
cloud-sql-proxy = "latest"
cocoapods = "latest"
fastfetch = "latest"
flutter = "latest"
fzf = "latest"
gcloud = "latest"
gemini-cli = "latest"
ghq = "latest"
github-cli = "latest"
go = "latest"
java = "corretto-21.0.8.9.1"
jq = "latest"
neovim = "latest"
node = "latest"
opencode = "0.15.31"
pipx = "latest"
poetry = "latest"
ruby = "3.3.9"
rust = "latest"
terraform = "latest"
usage = "latest"
uv = "latest"
yarn = "latest"
yq = "latest"

[settings]
idiomatic_version_file_enable_tools = []
trusted_config_paths = ["~/dotfiles", "~/ghq"]
